name: Python package

on:
  push:
    branches:
    - main
  # uncomment below if the workflow must run for every push in the PR branch
  pull_request:
    branches:
    - main

jobs:

  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macOS-latest]
        python-version: [3.8]
    name: Build for Python ${{ matrix.python-version }}
    steps:
      - uses: actions/checkout@v4
      - name: Setup conda
        uses: s-weigand/setup-conda@v1
        with:
          update-conda: true
          python-version: ${{ matrix.python-version }}
          conda-channels: psi4, conda-forge, anaconda
      - name: Check conda
        run: |
          conda --version
          echo "$CONDA_PREFIX"
      - name: Check Python
        run: which python
      - name: Install conda packages
        run: |
          conda install -c psi4 psi4
      #- name: actions-setup-cmake
      #  uses: jwlawson/actions-setup-cmake@v1.14.1
      #- name: Cmake info
      #  shell: bash -l {0}
      #  run: cmake --version
      #- name: Conda info
      #  shell: bash -l {0}
      #  run: |
      #    conda info
      #    conda list
      #    conda config --show-sources
      #    conda config --show
      #- name: Python info
      #  shell: bash -l {0}
      #  run: |
      #    which python
      #    python --version
      #- name: Install qc2
      #  run: |
      #    python3 -m install --upgrade setuptools
      #    python3 -m install .[dev,publishing,pennylane]
      ##- name: Setting up PSI4
      ##  shell: bash -l {0}
      ##  run : |
      ##   echo "PYTHONPATH=$CONDA_PREFIX/lib:$PYTHONPATH" >> $GITHUB_ENV
      ##   echo "$CONDA_PREFIX/bin" >> $GITHUB_PATH
      #- name: PSI4 info
      #  shell: bash -l {0}
      #  run : |
      #    which psi4
      #    psi4 --version
      #    python3 -c "import psi4"
      ##- name: Setup GNU Fortran
      ##  uses: modflowpy/install-gfortran-action@v1
      ##- name: Rose install for tests
      ##  run: |
      ##    git clone https://git@gitlab.com:Cmurilochem/rose.git  # https://gitlab.com/quantum_rose/rose.git
      ##    cd rose
      ##    git checkout ROSE_ase_calculator
      ##    cmake -S . -B build
      ##    cmake --build build
      ##    cmake --install build
      ##    echo `pwd`/bin >> $GITHUB_PATH
      ##    cd ..
      ##- name: DIRAC install for tests
      ##  run: |
      ##    zenodo_get -d 10.5281/zenodo.7670749
      ##    tar -xvf DIRAC-23.0-Source.tgz
      ##    cd DIRAC-23.0-Source
      ##    ./setup
      ##    cd build
      ##    make
      ##    echo `pwd`/bin >> $GITHUB_PATH
      ##    cd ..
      #- name: Run unit tests
      #  run: |
      #    pytest -v --pyargs tests/unit_tests
      ##- name: Run integration tests
      ##  run: |
      ##    pytest -v --pyargs tests/integration_tests
      ##- name: Verify that we can build the package
      ##  run: python3 setup.py sdist bdist_wheel
